




/*
     FILE ARCHIVED ON 7:13:58 Jun 27, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 11:26:49 Nov 12, 2013.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
langs['fr'] = {
	"(base value)":"(Valeur de base)",
	"Accelerate reflexes, granting the time to line up the perfect shot.":"Améliore les réflexes, accordant plus de temps pour aligner un tir parfait",
	"Accuracy":"Précision",
	"Accuracy & Firing Rate":"Précision et cadence de tir",
	"Accuracy Bonus":"Bonus de précision",
	"Add a biotic effect to a target that can be detonated.":"Ajoute un effet biotique de détonation sur une cible.",
	"Add a fire effect to targets, dealing 50% additional damaage over 6 seconds.":"Ajoute un effet de feu qui inflige 50% de dégâts supplémentaires pendant 6 secondes aux cibles touchées.",
	"Add an electric effect that does 40% additional damage over 10 seconds.":"Ajoute un effet electrique qui inflige 40% de dégâts supplémentaires pendant 10 secondes.",
	"Add an electric effect to a target that can be detonated. Increase damage by 50% for an additional 7.5 seconds.":"Ajoute un effet electrique de détonation sur une cible. Dégâts accrus de 50% pendant 7,5 secondes.",
	"Additional enemies can be lifted before singularity fades.":"D'autres cibles peuvent être lévitées avant la fin de l'effet.",
	"Adept":"Adepte",
	"Adrenaline Rush":"Montée d'Adrénaline",
	"Advanced Hardware":"Matériel avancé",
	"Alliance Training":"Entrainement de l'alliance",
	"Allied Protection":"Protection des alliés",
	"Allied Shields Restored":"Boucliers alliés restaurés",
	"all weapons":"toutes les armes",
	"Ammo Drop Frequency":"Fréquence de réapprovisionnement",
	"Amplification":"Amplification",
	"Annihilation Field":"Champ d'Annihilation",
	"Arc Grenade":"Grenade à Arc",
	"Arc Grenade (Earth)":"Grenade à Arc",
	"Area Scan":"Scan de zone",
	"Armor-Piercing":"Munitions perforantes",
	"Armor-Piercing Ammo":"Munitions perforantes",
	"Armor Boost":"Amélioration du blindage",
	"Armor Damage":"Dégâts contre l'armure",
	"Armor damage":"Dégâts contre l'armure",
	"ARs & SRs":"Fusil d'assaut & Fusils de précision",
	"Asari":"Asari",
	"Asari Adept":"Adepte Asari",
	"Asari Justicar":"Probatrice Asari",
	"Assault Rifles":"Fusil d'assaut",
	"Assault Rifles & Sniper Rifles":"Fusil d'assaut & Fusils de précision",
	"A vorcha's adaptable nature gives them advantages in combat. More power damage. More weapon damage. More strength. ":"L'adaptabilité des Vortchas leur donne l'avantage au combat. Dégâts des pouvoirs accrus. Dégâts des armes accrus. Puissance accrue.",
	"Backfire":"Défaillance",
	"Ballistic Blades":"Lames Balistiques",
	"Barrier":"Barrière",
	"Barrier Cost":"Barrière drainée",
	"Barrier Restored":"Barrière restaurée",
	"Barriers & Armor":"Barrières et Armure",
	"Barrier Strength":"Force de la barrière",
	"Base Omni-Shield Health: 3000":"Santé de l'Omnibouclier: 3000",
	"Batarian":"Butarien",
	"Batarian Enforcer":"Agent Butarien",
	"Battlefield 3":"Battlefield 3",
	"Berserk":"Fureur",
	"Biotic":"Biotique",
	"Biotic Charge":"Charge Biotique",
	"Biotic Charge (K)":"Charge Biotique",
	"Biotic Slash":"Taillade biotique",
	"Biotic Sphere":"Sphère biotique",
	"Blade Armor":"Armure anti-lame",
	"Blades explode after 3 seconds, doing damage but ending the bleed effect.":"Les lames explosent au bout de 3 secondes, infligeant 400 points de dégats mais mettant un terme à l'hémorragie.",
	"Blast Damage":"Dégâts de l'explosion",
	"Blast Effect":"Effet de souffle",
	"Blast Radius":"Rayon d'effet",
	"Bleed Damage":"Dégâts de saignement",
	"Bloodlust":"Soif de sang",
	"Bloodlust Stack 1":"Soif de sang Réserve 1",
	"Bonus Power":"Pouvoir supplémentaire",
	"Boost heal":"Amélioration de santé",
	"Boost health, shields, melee damage, durability, and movement speed.":"Améliore la santé, les boucliers, les dégâts au corps de corps et la durabilité.",
	"Boost weapon accuracy and firing rate for a short time.":"Améliore la précision et la cadence de tir de l'arme pendant un bref instant.",
	"Bubble":"Bulle",
	"Burning Damage":"Dégâts incendiaires",
	"Capacity":"Capacité",
	"Carnage":"Carnage",
	"Chain Lightning":"Eclairs enchainés",
	"Chain Overload":"Surcharge en chaîne",
	"Charge your sword with biotic energy and slash nearby enemies in a wide swath, flattening unshielded opponents.":"Charge votre épée d'énergie biotique et taille dans vos ennemis en un grand arc, écrasant les adversaires dépourvus de boucliers.",
	"Cluster-bomb a small area with incendiary munitions.":"Cette bombe incendie une petite zone",
	"Cluster Grenade":"Bombe à fragmentation",
	"Cobra Missiles":"Lance-missile cobra",
	"Combat Drone":"Drone de combat",
	"Combat skills are perfected to an art with N7 training. More power damage, more weapon damage, more strength.":"Grâce à l'entraînement N7, les compétences de combat deviennet un art. Dégâts des pouvoirs améliorés. Dégâts des armes améliorés. Force améliorée.",
	"Concussive Shot":"Tir percussif",
	"Cone Spread":"Dispersion",
	"Create a sphere of dark energy that traps and dangles enemies caught in its field.":"Crée une sphère d'énergie noire qui piège et suspend les ennemis pris dans son champ dans les airs.",
	"Cryo Ammo":"Munitions cryo",
	"Cryo Blast":"Souffle cryo",
	"Cryo Explosion":"Explosion cryo",
	"Cryo Shield":"Bouclier cryo",
	"Damage":"Dégâts",
	"Damage & Ammo":"Dégâts et munitions",
	"Damage & Bleed":"Dégâts et hémorragie",
	"Damage & Capacity":"Dégâts et capacité",
	"Damage & Duration":"Dégâts et durée",
	"Damage & Force":"Dégâts et force",
	"Damage & Max Grenades":"Dégâts et nombre de grenades",
	"Damage & Radius":"Dégâts et rayon d'effet",
	"Damage & Slow":"Dégâts et ralentissements",
	"Damage & Stability":"Dégâts et stabilité",
	"Damage and Weakness":"Dégâts et faiblesse",
	"Damage Bonus":"Bonus aux dégâts",
	"Damage Combo":"Combo dégâts",
	"Damage Over Time":"Dégâts sur la durée",
	"Damage Per Second":"Dégâts par seconde",
	"Damage Protection":"Protection",
	"Damage Reduction":"Réduction de dégâts",
	"Damage Returned":"Dégâts au corps à corps renvoyés",
	"Damage Taken":"Dégâts encaissés",
	"Damage Taken Bonus":"Bonus de dégâts reçus",
	"Damage Taken Increase":"Augmentation des dégâts reçus",
	"Dark Channel":"Canalisation Sombre",
	"Deal 150% more damage to targets before Stasis breaks.":"Dégâts accrus de 150% avant la fin de la Stase.",
	"Deal damage across 6 meters every 1.50 seconds.":"Inflige des dégâts sur une distance de 6 m chaque 1,50 seconde",
	"Decoy":"Leurre",
	"Decoy explodes on destruction, causing 300 damage across 4 meters.":"Le leurre explose lorsqu\'il est détruit, infligeant 300 points de dégâts dans un rayon de 4 mètres.",
	"Decoy explodes on destruction.":"Le leurre explose lorsqu\'il est détruit.",
	"Decoy Shields":"Boucliers leurre",
	"Decrease Health and Shield damage taken by 40%.":"Diminue les dégâts infligés à votre santé et à vos boucliers de 40%.",
	"Decrease shield recharge delay by 10%.":"Diminue le délai de rechargement de votre bouclier de 10%.",
	"Decrease shield recharge delay by 15%.":"Diminue le délai de rechargement de votre bouclier de 15%.",
	"Decrease weapon damage mitigation of armored targets by 50% for 8 seconds.":"Diminue la résistance aux dégâts des armes des cibles en armure de 50% durant 8 secondes.",
	"Deploy an immobile pylon that supplies ammo and grenades. A built-in tech generator also increases maximum shields for nearby allies. Only one pylon can be active at a time.":"Déploie un pylône immobile qui fournit munitions et grenades.Un générateur technologique intégré augmente aussi les boucliers max de tous les alliés proches. Un seul pylône peut être actif à la fois.",
	"Deploy this attack drone to stun targets and draw enemy fire.":"Déployez ce drone d\'attaque pour étourdir vos cibles et attirer le feu adverse.",
	"Deploy this heavy-weapon turret for cover fire.":"Déploie une tourelle multifonction qui inflige des dégâts lourds et répare les boucliers.",
	"Deploy this heavy-weapon turret for cover fire. Fires 3-round bursts.":"Déploie une tourelle multifonction qui inflige des dégâts lourds et répare les boucliers. Tire par à-coups de 3 coups.",
	"Detonate":"Détonation",
	"Detonate Singularity when the field dies to inflict damage across 7 meters.":"Provoque l\'explosion de la singularité quand le champ expire, infligeant points de dégâts sur un rayon de 7 mètres.",
	"Devastator Mode":"Mode Dévastateur",
	"Distract opponents with this decoy.":"Ce leurre distrait les ennemis.",
	"Do an additional 100% damage over 10 seconds.":"Inflige 100% de dégâts supplémentaires pendant 10 secondes.",
	"Drain":"Drain",
	"Drain 100% of the damage done to enemy shields/barriers to restore your own shields.":"Draîne 100% des dégâts infligés aux boucliers ou aux barrières dverses pour recharger vos propres boucliers.",
	"Drain a target's health and disrupt their resistances, receiving increased damage protection while this power is in effect.":"Draine la santé de la cible et neutralise ses résistances, augmentant votre protection contre les dégâts tant que ce pouvoir fait effet.",
	"Drell":"Drell",
	"Drell Assassin":"Assassin Drell",
	"Drive the lash into the ground to cause area-of-effect damage and devastating direct damage.":"Libérer un impact au sol peut entraîner des dégâts directs dévastateurs sur l\'aire d\'effet.",
	"Drone Damage":"Dégats de drone",
	"Drone explodes when destroyed, dealing damage across a 5 meter radius.":"Amélire votre drone de combat. Sa destruction entraîne une explosion gigantesque qui inflige points de dégats à toutes les cibles se trouvant dans un rayon de 5 mètres.",
	"Drone Shields":"Boucliers de drone",
	"Durability":"Durabilité",
	"Duration":"Durée",
	"Duration & Combos":"Durée et combos",
	"Duration & Radius":"Durée et rayon",
	"Duration and Slow":"Durée et ralentissement",
	"effects":"effets",
	"Efficient Blast":"Emission efficace",
	"Electrical Damage":"Dégât électrique",
	"Electric Damage":"Dégât électrique",
	"Electric Field":"Champ électrique",
	"Electric Field Damage":"Dégâts du champ électrique",
	"Electric Slash":"Taillade électrique",
	"enc":"enc.",
	"Enemy Weakness":"Faiblesse ennemie",
	"Energy Drain":"Drain d'énergie",
	"Engineer":"Ingénieur",
	"Enhanced Vision Range":"",
	"Entangle opponents in an electrified net, dealing massive damage to armored targets and incapacitating unarmored targets as they break free. Targets build up resistance to the grappling effects of the net.":"",
	"Ex-Cerberus":"Humain",
	"Expand":"",
	"Expand the Singularity field by 35% for 10 seconds.":"",
	"Exploding Decoy":"Leurre Explosif",
	"Explosion Damage":"",
	"Explosion Radius":"",
	"Explosive Blades":"",
	"Explosive Hack":"",
	"Expose":"Exposition",
	"Extra Grenade":"Grenade supplémentaire",
	"Fast recharge":"Rechargement rapide",
	"Fire Damage":"Dégâts de feu",
	"Fire one power while cloaked and remain hidden.":"",
	"Fire Shield":"Bouclier incendiaire",
	"Fire this sticky mine into traffic. It will detonate when an enemy steps within range.":"",
	"Firing Rate":"Cadence de tir",
	"Fitness":"Athlète",
	"Fitness (A/Q/S)":"Athlète",
	"Fitness (B/H/T)":"Athlète",
	"Fitness (D)":"Athlète",
	"Fitness (Ex-C)":"Athlète",
	"Fitness (QM/V)":"Athlète",
	"Fitness Expert":"Athlète accompli",
	"Flame-thrower":"Lance-flammes",
	"Flamer":"Pyromane",
	"Flamethrower":"",
	"Flamethrower Damage":"",
	"Flash-freeze unprotected enemies and slow down the rest with a wave of ice damage. Frozen targets don't regenerate health. Weaken armor by 25%.":"",
	"Focus the energy of your barrier to fire a high-powered beam at a target from afar. Firing the beam consumes 50% of max barriers.":"",
	"Force":"Force",
	"Force":"Force",
	"Force & Damage":"Force et dégâts",
	"Fortification":"Fortification",
	"Frag Grenade":"Grenade frag.",
	"Freeze Combo":"Combo cryo",
	"Freeze Duration":"",
	"Frozen Vulnerability":"",
	"Gain the option to use nova two times in a row by reducing its barrier consumption by 50% but at the cost of reducing damage and force by 40%.":"",
	"Geth":"Geth",
	"Geth Turret":"Tourelle geth",
	"Geth Weapon Damage Bonus":"",
	"Give biotic charge a 33% chance of not triggering a cooldown.":"",
	"Give the power a 35% chance of not causing a cooldown. Increase the time lifted targets can be detonated by 100%.":"",
	"Grapple Duration":"",
	"Grenade Capacity Bonus":"",
	"Grenade Count":"",
	"Grenade Drop Frequency":"",
	"Grenades stay active for 15 seconds when attached to a wall or surface, exploding when an enemy approaches.":"",
	"Hack Duration":"",
	"Hacked synthetics fighting on your side move faster and do 50% more damage.":"",
	"Half Blast":"Demi-explosion",
	"Hardening":"Durcissement",
	"Headshot Damage Bonus":"",
	"Headshots":"Tirs à la tête",
	"Health & Shields Bonus":"",
	"Health/Shields":"",
	"Health Regen-eration":"Rénéneration de la santé",
	"Health Regeneration":"Rénéneration de la santé",
	"Heavy Pistols":"Pistolet",
	"Hit an enemy with this energy pulse to inflict damage and to steal barrier and shield power.":"",
	"Hit up to 2 additional targets within 2 meters of the impact point.":"",
	"Hit up to one additional target within 8 meters with 60% less damage.":"",
	"hmelee":"corps à corps lourd",
	"Homing Grenade":"Grenade à tête chercheuse",
	"Human":"Humain",
	"Hunter Mode":"Mode Chasseur",
	"Hydra Missiles":"Missiles Hydre",
	"Impact Radius":"Aire d'effet",
	"Incapacitate":"Paralysie",
	"Incapacitate Duration":"",
	"Incapacitate enemies by knocking them down.":"",
	"Incapacitate weaker organic enemies for a short duration.":"",
	"Incinerate":"Incinération",
	"Increase all damage done to target by 50%.Deal 35% more damage to targets before Stasis breaks.":"",
	"Increase all damage to targets lifted by Pull by 30%.":"",
	"Increase all headshot damage by 25%.":"",
	"Increase all power damage done to the target by 7.5%.":"",
	"Increase all tech power damage done to target by 50% for 10 seconds.":"",
	"Increase all weapon damage done to the target by 7.5%.":"",
	"Increase cone spread by 20 degrees.":"",
	"Increase damage by an additional 50% over 8 seconds.":"",
	"Increase damage dealt to target from all sources by 20% for 8 seconds.":"",
	"Increase damage done to armor by 50%.":"",
	"Increase damage of all powers by 15% while active.":"",
	"Increase damage to already lifted targets by 100%.":"",
	"Increase damage to armor by 50%.":"",
	"Increase damage to armor by 60%.":"",
	"Increase damage to armor by 75%.":"",
	"Increase damage to armored targets by 50%.":"",
	"Increase damage to armored units by 50%.":"",
	"Increase damage to armored units by 65%.":"",
	"Increase damage to barriers, shields, and armored targets by 100%.":"",
	"Increase damage to barriers and armor by 50%. Weaken armored targets by an additional 25%":"",
	"Increase damage to barriers and armor by 75%.":"",
	"Increase damage to barriers and shields by an additional 100%.":"",
	"Increase damage to chilled and frozen targets by 10%.":"",
	"Increase damage to frozen and chilled targets by 15%. Weaken armored targets by an additional 25%.":"",
	"Increase damage to frozen and chilled targets by an additional 100%.":"",
	"Increase damage to organics by 50% over 10 seconds.":"",
	"Increase damage to organics by 100% over 10 seconds.":"",
	"Increase damage to shields & barriers by 50%.":"",
	"Increase damage to shields and barriers by 50%.":"",
	"Increase damage to shields by 75%.":"",
	"Increase damage to shields/barriers by 75%.":"",
	"Increase effectiveness against armor and barriers by 75%.":"",
	"Increase effectiveness against armored targets by 50%.":"",
	"Increase force, damage and impact radius of combo detonations by 50%.":"",
	"Increase force and damage of biotic detonations by 50%.":"",
	"Increase force and damage of biotic detonations by 65%.":"",
	"Increase force and damage of tech detonations by 100%.":"",
	"Increase force and damage to frozen targets by 100%.":"",
	"Increase force by 50%, and do an additional 200 damage on impact.":"",
	"Increase headshot damage by 25%.":"",
	"Increase health regeneration of each stack by 50%.":"",
	"Increase health regeneration of each stack by an additional 100%.":"",
	"Increase impact radius by 1.5 meters.":"",
	"Increase impact radius by 2 meters.":"",
	"Increase impact radius by 2.5 meters.":"",
	"Increase impact radius by 3 meters.":"",
	"Increase max shields by 40%.":"",
	"Increase melee damage 40% while armor is active.":"",
	"Increase melee damage by 40% for 5 seconds after a successful biotic charge.":"",
	"Increase melee damage by 50%.":"",
	"Increase melee damage by 50% while cloaked.":"",
	"Increase melee damage by 75% for 30 seconds after an enemy is killed by a heavy melee.":"",
	"Increase melee damage by 75% for 30 seconds when an enemy is killed by heavy melee.":"",
	"Increase melee damage of each stack by 10%.":"",
	"Increase power damage and force by 20% while Fortification is active.":"",
	"Increase power damage and force by 30% while armor is active.":"",
	"Increase power damage and force by 40% for 10s after a successful biotic charge.":"",
	"Increase power damage bonus by 25% for 20 seconds after an enemy is killed by heavy melee.":"",
	"Increase power damage bonus by 30% for 20 seconds after an enemy is killed by heavy melee.":"",
	"Increase power damage bonus of each stack by 5%.":"",
	"Increase rate of fire of all weapons by 15% while active.":"",
	"Increase recharge speed of all powers by 20% while active.":"",
	"Increase recharge speed of all powers by 25% for 15 seconds.":"",
	"Increase shield recharge rate by 15%":"",
	"Increase shield recharge rate by 15%.":"",
	"Increase shield regeneration rate by 15% while Barrier is active.":"",
	"Increase shield restoration rate by 50% when draining shields, barriers, or power from synthetic enemies.":"",
	"Increase shield strength by 100%.":"",
	"Increase Shrapnel by 1 fragment.":"",
	"Increase shrapnel count by 1.":"",
	"Increase sniper rifle damage by 25% while cloaked.":"",
	"Increase sword damage by 50% for 20 seconds after an enemy is killed by a sword attack.":"",
	"Increase sword damage to armor by 50%.":"",
	"Increase sword damage to shields/barriers by 50%.":"",
	"Increase the damage of tech combos by 100%.":"",
	"Increase the duration by 50%, and increase the force and damage of biotic detonations on affected targets by 75%.":"",
	"Increase the frequency of restoring shields by 60%.":"",
	"Increase the number of grenades generated by 1.":"",
	"Increase the number of grenades launched by 2.":"",
	"Increase the number of targets hit by 1.":"",
	"Increase the range of this ability by 40%.":"",
	"Increase weapon accuracy by 25% while active.":"",
	"Increase weapon damage bonus by 25% for 20 seconds after an enemy is killed by heavy melee.":"",
	"Increase weapon damage bonus by 30% for 20 seconds after an enemy is killed by heavy melee.":"",
	"Increase weapon damage bonus of each stack by 5%.":"",
	"Increase weapon damage by 25% for 5s after a successful biotic charge.":"",
	"Increase weapon damage by 25% for 20 seconds after an enemy is killed by a heavy melee.":"",
	"Increase weapon damage taken by a target by 15%. Increase power damage taken by a target by 15% for 10 seconds.":"",
	"Inferno Grenade":"Grenade Inferno",
	"Infiltrator":"Franc-Tireur",
	"Inflict 50 damage per second to lifted targets.":"",
	"Keep allies within the shield to decrease shield-recharge delay by 15%.":"",
	"Knockdown":"Mise à terre",
	"Knock weaker enemies to the ground.":"",
	"Krogan":"Krogan",
	"Krogan Battlemaster":"Foudre de guerre Krogan",
	"Krogan Berserker":"Berserker Krogan",
	"Krogan BM":"Foudre de guerre Krogan",
	"Lash":"Impact",
	"Lasting Damage":"Dégâts persistants",
	"Latch this biotic field onto enemies to jerk them towards you, doing massive damage in the process.":"",
	"Launch this seeking grenade to track down a target, causing a massive explosion on impact.":"",
	"Lift Damage":"Dégâts de lévitation",
	"Lift Grenade":"Grenade de lévitation",
	"Lifting Shockwave":"Onde de choc lévitante",
	"Lob this biotic grenade at enemies and watch them fly.":"",
	"Magazine Size":"Taille du magasin",
	"Magazine Size Bonus":"",
	"Marksman":"Tireur d'élite",
	"Martial Artist":"Maître arts martiaux",
	"Max Grenades":"Grenades max",
	"Max Shield Increase":"",
	"Max Shields":"Boucliers max",
	"melee":"corps à corps",
	"Melee Damage":"Dégât corps à corps",
	"Melee Damage Bonus":"Bonus de dégâts au corps à corps",
	"Melee Damage Duration":"",
	"Melee Damage Returned":"",
	"Melee/Heavy Melee":"",
	"Melee Synergy":"Synergie des pouvoirs",
	"Missile Damage":"Dégâts de missile",
	"Missile Launcher":"Lance-missiles",
	"Missile Recharge Speed":"Vitesse de rechargement des missiles",
	"Momentarily reveal enemies withn 20m of the target with an inital scanning pulse.":"",
	"Movement & Melee":"Déplacements et corps à corps",
	"Movement Speed":"Vitesse de déplacement",
	"Movement Speed Bonus":"",
	"Movement Speed Penalty":"",
	"Multi-Frag Grenade":"Grenade multi-frag",
	"N7 Demolisher":"Prédateur N7",
	"N7 Destroyer":"Destroyer N7",
	"N7 Fury":"Furie N7",
	"N7 Paladin":"Paladin N7",
	"N7 Paladin/Fury":"Furie/Paladin N7",
	"N7 Shadow":"Ombre N7",
	"N7 Slayer":"Fendeur N7",
	"Networked AI":"I.A. en réseau",
	"Neural Shock":"Choc neuronal",
	"Nova":"Nova",
	"Nova gains a 25% chance of not using up barriers.":"",
	"Omni-Shield Health":"Santé de l'OmniBouclier",
	"Overload":"Surcharge",
	"Penetrate through shields and barriers, lifting any target without armor but with reduced force.":"",
	"Phase Disruptor":"Antigrav phasique",
	"Phoenix Training":"Entraînement Phénix",
	"Pierce":"Pénétration",
	"Pistols":"Pistolets",
	"Pistols & Shotguns":"Pistolets et fusils à pompe",
	"Points left":"",
	"Power Concussive Shot with the properties of the active ammo power, enabling it to burn, freeze, disrupt, warp, or pierce armor.":"",
	"Power Damage":"Dégâts des pouvoirs",
	"Power Damage Bonus":"",
	"Power Duration Bonus":"",
	"Power Recharge":"Rechargement de pouvoir",
	"Power Synergy":"Synergie des pouvoirs",
	"Power Use":"Utilisation de pouvoir",
	"Proximity Mine":"Mine de proximité",
	"Proximity Trap":"Piège de proximité",
	"Pull":"Télékinésie",
	"Pure Rage":"Rage pure",
	"Quarian":"Quarien",
	"Quarian Defender":"Défenseur quarien",
	"Quarian Defender (M)":"Défenseur quarien (M)",
	"Quarian Male":"Quarien (M)",
	"Radius":"Rayon",
	"Radius & Shrapnel":"Rayon d'effet et éclats d'obus",
	"Rage":"Rage",
	"Range":"Portée",
	"Rate-of-Fire Bonus":"Bonus de cadence de tir",
	"Rate of Fire":"Cadence de tir",
	"Reach":"Portée",
	"Reave":"Rupture",
	"Reave (AJA)":"Rupture(AP)",
	"Reave (DA)":"Rupture(DA)",
	"Recharge Combo":"Combo de rechargement",
	"Recharge Speed":"Vitesse de rechargement",
	"Reduce all damage taken by 40% for 5 seconds after decloaking.":"",
	"Reduce damage taken by 40% for 10 seconds by gaining a temporary layer of armor by draining shields, barriers, or energy from synthetics.":"",
	"Reduce power speed penalty by 30%.":"",
	"Reduce the delay before shields start regenerating by 15%.":"",
	"Reduce the number of melee kills required to trigger Rage to 2 within 30 seconds.":"",
	"Refire Time":"Délai avant tir",
	"Reinforce Armor with razor-sharp blades that damage enemies that melee.":"",
	"Reset recharge time after a biotic combo detonates.":"",
	"Restore Frequency":"Fréquence de restauration",
	"Restore Range":"Portée de restauration",
	"Resupply Frequency":"Fréquence de rechargement",
	"Rip your enemies apart with this shrapnel-packed grenade.":"",
	"Rocket Damage":"",
	"Rockets":"Lance-missile",
	"Sabotage":"Sabotage",
	"Salarian":"Galarien",
	"Salarian Operative":"Agent Galarien",
	"Sentinel":"Sentinelle",
	"Sentry Turret":"Tourelle de garde",
	"Shadow Strike":"Frappe de l'ombre",
	"Shatter":"Démolition",
	"Shield & Barrier":"Boucliers et barrières",
	"Shield & Duration":"Boucliers et durée",
	"Shield Bonus":"",
	"Shield Boost":"Recharge de bouclier",
	"Shield Damage":"Dégâts aux boucliers",
	"Shield Drain":"Drain de bouclier",
	"Shield Durability":"Durabilité de bouclier",
	"Shield Mastery":"Maîtrise du bouclier",
	"Shield Overload":"Surcharge bouclier",
	"Shield Penalty":"Pénalité de bouclier",
	"Shield Penetration":"Pénétration du bouclier",
	"Shield Recharge":"Recharge de bouclier",
	"Shield Recharge & Speed":"Recharge de bouclier",
	"Shield Recharge Delay":"Délai de rechargement des boucliers",
	"Shield Regen-eration":"Régénération de bouclier",
	"Shield Regeneration":"Régénération de bouclier",
	"Shield Restore":"Restauration des boucliers",
	"shields":"Boucliers",
	"Shields & Damage":"Boucliers et dégâts",
	"Shields Restored":"",
	"Shock":"Choc",
	"Shock enemies for 100 points within a 2.50 meter radius of the decoy.":"",
	"Shockwave":"Ondes de choc",
	"Shotguns":"Fusils à pompe",
	"Shotguns & Assault Rifles":"Fusils à pompe et fusils d'assaut",
	"Shrapnel":"Eclats d'obus",
	"Shredder":"Shredder",
	"Singularity":"Singularité",
	"skills":"pouvoirs",
	"Slam":"Lévitation",
	"Slam floating targets to the ground as Lift wears off, stunning them for 3 seconds.":"",
	"s length depends on Dark Channel":"",
	"Slow":"",
	"Slow armored targets by 30% for 10 seconds.":"",
	"Slows target's movement speed by 30%.":"",
	"Slow target's movement speed by 30% for 8 seconds.":"",
	"Smash":"Frapper",
	"SMGs":"Mitraillettes",
	"Snap Freeze":"Gel instantané",
	"Sniper & Shotguns":"Fusils de précision et fusils à pompe",
	"Sniper Damage":"Dégâts de sniper",
	"Sniper Rifles":"Fusils de précision",
	"Soldier":"Soldat",
	"Spare Ammo Bonus":"",
	"Spare Ammo Bonus: 10%":"",
	"Spare Ammo Bonus: +5%":"",
	"Spare Ammo Bonus: +10%":"",
	"Special":"",
	"Speed & Vision":"Vitesse et vision",
	"Speed Reduction":"Réduction de vitesse",
	"Spin this fiery effect around you to burn nearby enemies. When active, the field can be recast to blast a short-range area and to detonate combos.":"",
	"Split a grenade in half to seek two targets that do 60% damage each.":"",
	"Split Grenade":"Grenade divisée",
	"Stasis":"Stase",
	"Stasis Strength":"Puissance de Stase",
	"Stick this grenade to your oponent and the explosion will tear apart the target and the shrapnel will damage other targets caught in the blast.":"",
	"Sticky Grenade":"Bombe collante",
	"Submission Net":"Filet de soumission",
	"Supply Pylon":"Pylône ravitailleur",
	"Suspend targets in the air for a short time.":"",
	"Sustain":"Alimentation",
	"Sword Damage":"Dégâts de l’épée",
	"Sword Mastery":"Maîtrise de l’épée",
	"Synthetics explode when destroyed, dealing 350 points of damage across a 4 meter radius.":"",
	"Synthetics explode when destroyed.":"",
	"T5-V Battlesuit":"Exosquelette de combat T5-V",
	"T5-V Internal Systems":"Systèmes internes du T5-V",
	"Tactical Cloak":"Camouflage tactique",
	"Tactical Scan":"Scan tactique",
	"Targets caught in the field take 15% additional damage from all sources.":"",
	"Tech":"Tech",
	"Tech Armor":"Technoblindage",
	"Tech Combo":"Combo tech",
	"Tech Vulnerability":"Vulnérabilité techno",
	"Throw":"Projection",
	"t make much sense and it":"",
	"Topple a row of enemies with this cascading shockwave.":"",
	"Toss your enemy through the air with this biotic blast.":"",
	"t regenerate health.":"",
	"Turian":"Turien",
	"Turian Veteran":"Vétéran Turien",
	"Turret Damage":"",
	"Turret Shields":"",
	"Unleash a Stasis bubble to trap enemies that walk into it.":"",
	"Upgrade drone's electrical pulse to jump and hit 3 additional targets.":"",
	"Upgrade drone's short-range attack to deal 130 points of damage across a 2.50 meter radius. Drone stuns enemies for a short duration.":"",
	"Upgrade drone with long-range rockets that deal damage across a 2 meter radius.":"",
	"Upgrade missile housing to fire 2 extra seeking projectiles. Decreases the payload of each missile by 25%.":"",
	"Upgrade the cutting-edge T5-V Battlesuit. More power damage. More weapon damage. More strength.":"",
	"Upgrade the T5-V's internal systems to boost health, shields, melee damage, and durability.":"",
	"Upgrade the tech generator to also increase allied power damage by 15%.":"",
	"Upgrade the tech generator to also increase allied weapon damage by 15%.":"",
	"Upgrade turret with a close-range flamethrower.":"",
	"Upgrade turret with armor-piercing ammo, giving it a 100% damage bonus against armor.":"",
	"Upgrade turret with cryo ammo, giving it a chance to freeze enemies for 3 seconds.":"",
	"Upgrade turret with long-range rockets that deal damage across a 2.5 meter radius.":"",
	"Upgrade turret with shock attack to stun enemies.":"",
	"Upgrade with a close-range flamethrower that deals 71.5 points of damage per second.":"",
	"Use 1 offensive power while Adrenaline Rush is active.":"",
	"Use two powers in a row by giving the first power a 30% chance to cause no cooldown.":"",
	"Vanguard":"Porte-Etendard",
	"Vorcha":"Vortcha",
	"Vorcha Resilience":"Résistance vortcha",
	"Vulnerability":"Vulnérabilité",
	"Warp":"Déchirure",
	"Warp Effect":"Déchirure",
	"Weaken armored targets by an additional 25%.":"",
	"Weapon":"Arme",
	"Weapon Accuracy":"Précision des armes",
	"Weapon Damage":"Dégâts des armes",
	"Weapon Damage Bonus":"",
	"Weapon Damage Bonus":"",
	"Weapon Dmg & Max Grenades":"Dégâts des armes et grenades max",
	"Weapon Stability":"Stabilité des armes",
	"Weapon Stability Bonus":"",
	"Weapon Synergy":"Synergie de l’arme",
	"Weapon Weight":"Poids des armes",
	"Weapon Weight Reduction":"",
	"Weight Capacity Bonus":"",
	"Weight Cooldown Bonus":"",
	"Yank an enemy helplessly off the ground.":"",
	
	// gear
	"Assault Rifle Rail Amp":"Ampli de rail de fusil d'assaut",
	"Pistol Rail Amp":"Ampli de rail de pistolet",
	"Shotgun Rail Amp":"Ampli de rail de fusil à pompe",
	"SMG Rail Amp":"Ampli de rail de mitraillette",
	"Sniper Rifle Rail Amp":"Ampli de rail de fusil de précision",
	"Strength Enhancer":"Amplificateur de force",
	"Targeting VI":"I.V. de visée",
	
	"Adrenaline Module":"Module d'adrénaline",
	"Power Amplifier Module":"Module d'amplification de pouvoir",
	"Power Efficiency Module":"Module d'efficacité de pouvoir",
	"Cyclonic Modulator":"Modulateur cyclonique",
	"Shield Power Cells":"Accumulateurs de bouclier",
	"Stabilization Module":"Module de stabilisation",
	
	"Commando Package":"Pack de commando",
	"Berserker Package":"Pack de Berserker",
	"Expert Package":"Pack d'expert",
	"Operative Package":"Pack d'agent",
	"Stronghold Package":"Pack de la base",
	"Warfighter Package":"Pack de guerrier",
	"Mental Focuser":"Concentration mentale",
	"Structural Ergonomics":"Ergonomie structurelle",
	"Multicapacitor":"Condensateur multiple",
	"Shield Booster":"Recharge de bouclier",
	"Assault Rifle Amp":"Ampli de rail de fusil d'assaut",
	"Pistol Amp":"Ampli de rail de pistolet",
	"Shotgun Amp":"Ampli de rail de fusil à pompe",
	"SMG Amp":"Ampli de rail de mitraillette",
	"Sniper Rifle Amp":"Ampli de rail de fusil de précision",
	"Grenade Capacity":"Capacité en grenades",
	"Hydraulic Joints":"Joints hydrauliques",
	"Vulnerability VI":"IV blessante",
	"Adaptive War Amp":"Ampli de guerre adaptatif",
	"Combatives Upgrade":"Amélioration de combativité",
	"Densified Ammunition":"Munitions denses",
	"Engineering Kit":"Kit d’ingénierie",
	"Guerrilla Upgrade":"Amélioration de guérilla",
	"Juggernaut Shield":"Bouclier colossal",
	"Martial Biotic Amp":"Ampli biotique martial",
	"Omni-Capacitors":"OmniCondensateurs",
	"Shock Trooper Upgrade":"Amélioration de choc",
	"Thermal Clip Storage":"Stockage de cartouches thermiques",
	"Barrage Upgrade":"Amélioration de barrage",
	"Medi-Gel Transmitter":"Séc. médi-gel accrue",
	"Armored Compartments":"Compart. renforcés",
	"Responder Loadout":"Arsenal de réponse",
	"Survivor Loadout":"Arsenal du survivant",
	"Assault Loadout":"Arsenal d'assaut",
	
	// weapons
	"Avenger":"M-8 Avenger",
	"Cerberus Harrier":"Chasseur de Cerberus",
	"Collector AR":"Fusil d'assaut de Récolteur",
	"Falcon":"M-37 Falcon",
	"Geth Pulse Rifle":"Fusil à impulsion geth",
	"Mattock":"M-96 Mattock",
	"Phaeston":"Phaëton",
	"Revenant":"M-76 Revenant",
	"Saber":"M-99 Sabre",
	"Striker":"Fusil d'assaut Briseur",
	"Vindicator":"M-15 Vindicator",
	"Arc Pistol":"Pistolet à arc",
	"Carnifex":"M-6 Carnifex",
	"Eagle":"N7 Aigle",
	"Paladin":"M-77 Paladin",
	"Phalanx":"M5 Phalanx",
	"Predator":"M-3 Prédateur",
	"Scorpion":"Scorpion",
	"Talon":"M-358 Serre",
	"Claymore":"M-300 Claymore",
	"Crusader":"N7 Crusader",
	"Disciple":"Disciple",
	"Eviscerator":"Écorcheur M-22",
	"GPSG":"Fusil à pompe à plasma geth",
	"Graal Spike":"Lance-pic Graal",
	"Katana":"M-23 Katana",
	"Reegar Carbine":"Carabine Reegar",
	"Scimitar":"M-27 Cimeterre",
	"Wraith":"M-11 Éventreur",
	"GPSMG":"Mitrail. plasma geth",
	"Hornet":"M-25 Frelon",
	"Hurricane":"N7 Hurricane",
	"Locust":"M12 Locust",
	"Shuriken":"M-4 Shuriken",
	"Tempest":"M-9 Tempête",
	"Black Widow":"Veuve noire",
	"Incisor":"M-29 Incisor",
	"Indra":"M-90 Indra",
	"Javelin":"Javelot",
	"Kishock Harpoon":"Fusil harpons Kishock",
	"Krysae":"Fusil de précision Krysae",
	"Mantis":"M-92 Mantis",
	"Raptor":"M-13 Raptor",
	"Valiant":"N7 Valiant",
	"Viper":"M-97 Viper",
	"Widow":"M-98 Veuve",
	"N7 Typhoon":"N7 Typhon",
	"Acolyte":"Acolyte",
	"N7 Piranha":"N7 Piranha",
	"Particle Rifle":"Fusil à particules",
	"Argus Assault Rifle":"M-55 Argus",
	"AT-12 Raider":"Pirate AT-12",
	"Collector SR":"Fusil de précision Récolteur",
	"Collector SMG":"Mitraillette Récolteur",
	"N7 Valkyrie":"N7 Valkyrie",
	
	// weapon mods
	"Blade Attachment":"Baïonnette",
	"Cranial Trauma System":"Système de trauma crânien",
	"Enhanced Scope":"Lunette améliorée",
	"Extended Barrel":"Canon allongé",
	"Heat Sink":"Dissipateur thermique",
	"Heavy Barrel":"Canon lourd",
	"High Caliber Barrel":"Canon gros calibre",
	"High-Velocity Barrel":"Canon à haute-vélocité",
	"Magazine Upgrade":"Amélioration de chargeur",
	"Melee Stunner":"incapacitant pour corps à corps",
	"Omni-Blade":"OmniLame",
	"Piercing Mod":"Mod perforant",
	"Precision Scope":"Lunette de précision",
	"Recoil System":"Système de recul",
	"Scope":"Viseur",
	"Shredder Mod":"Mod déchirant",
	"Smart Choke":"Étranglement",
	"Spare Thermal Clip":"Réserve de cartouches thermiques",
	"Stability Damper":"Compensateur de recul",
	"Thermal Scope":"Lunette thermique",
	"Ultralight HP Materials":"Matériaux ultra-légers pour pistolet",
	"Ultralight SMG Materials":"Matériaux ultra-légers de la mitraillette"
}